# Site settings
title: Didactica aumentada 3.0
description: Esto es didactica aumentada 3.0
keywords: Moderno, Blog, Divertido
author: togga117
baseurl: "/blog-didactica-aumentada3.0" # the subpath of your site, e.g. /blog/
url: "https://togga117.github.io" # the base hostname & protocol for your site
